{% set version = "6.8" %}

package:
  name: texinfo
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/texinfo/texinfo-{{ version }}.tar.gz
  sha256: 8e09cf753ad1833695d2bac0f57dc3bd6bcbbfbf279450e1ba3bc2d7fb297d08
  patches:
    - osx_cross_compile_configure_sdkroot.patch  # [osx and build_platform != target_platform]

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - help2man
    - gettext
    - gawk
    - make
    - perl 5.*  # [build_platform != target_platform]
  host:
    - ncurses
    - libiconv  # [osx]
    - perl
  run:
    - perl

test:
  commands:
    - makeinfo -h

about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL-2.0-only and GPL-3.0-only
  license_file: COPYING
  summary: The GNU Documentation System

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
