# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LVeR+cEms/EOFS75W+N+1sUAnC5vZnqWoB5tcwWQZ188IYQOVR3QJowkEQo4vVx8Ak/Zrmp+0djwPsP6woUJrFiD67VpzrSSHjlOWG8ehcaXF1VvT7SrlaCAb42OxgPqKal1EXCAyNd4vDKlzvPHyqE7UTW/b0r1VJc3H9wD6QS55ZtdHowqojDrAUlTrodCI/J3u6wNcCoBl9DcyOYRDn+zJfbvr29agDZWTw087L7VKltuOyoISsuagRSph6HgKCoSPvacsXkqkrty/1vXbVKGuQs1ZDfw61djnJNBfQpov0gPh9ptmJGmcZBU/1nCCjVI25VmMCugjk+OaiN8pyOoxzUjDciCJteAFOs28uT7L+TvH0BL2W1po2C/yNPudpp3w/yWn+4fd9B6fLyvVT5TdrssfVqQ5alDjTB7Xu1ZkyMRU3FFvQ9BpwhJ6e/YUNf48j/CkK+jsH8G+WHrH7QXXFd5VC2EdD2TwhEjTXcwljsjEry2ItVEn2sAJCbXIwOuwcgM2EEeozQVobze4E5DJ8GFhcev9GY3JiqNmXi4BlhAIvsv5D1QlUhAy7/HAfY9mAjuuec84nCbJ7Ausymo7LPjWlNJFl26eZ/7nuP4NS9Vhw9C1XAmVODKDPPSoiDdS5xl4AYWO7NR5oYucsG0qeYlHP0gr093TuUEMIk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml