appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: LVeR+cEms/EOFS75W+N+1sUAnC5vZnqWoB5tcwWQZ188IYQOVR3QJowkEQo4vVx8Ak/Zrmp+0djwPsP6woUJrFiD67VpzrSSHjlOWG8ehcaXF1VvT7SrlaCAb42OxgPqKal1EXCAyNd4vDKlzvPHyqE7UTW/b0r1VJc3H9wD6QS55ZtdHowqojDrAUlTrodCI/J3u6wNcCoBl9DcyOYRDn+zJfbvr29agDZWTw087L7VKltuOyoISsuagRSph6HgKCoSPvacsXkqkrty/1vXbVKGuQs1ZDfw61djnJNBfQpov0gPh9ptmJGmcZBU/1nCCjVI25VmMCugjk+OaiN8pyOoxzUjDciCJteAFOs28uT7L+TvH0BL2W1po2C/yNPudpp3w/yWn+4fd9B6fLyvVT5TdrssfVqQ5alDjTB7Xu1ZkyMRU3FFvQ9BpwhJ6e/YUNf48j/CkK+jsH8G+WHrH7QXXFd5VC2EdD2TwhEjTXcwljsjEry2ItVEn2sAJCbXIwOuwcgM2EEeozQVobze4E5DJ8GFhcev9GY3JiqNmXi4BlhAIvsv5D1QlUhAy7/HAfY9mAjuuec84nCbJ7Ausymo7LPjWlNJFl26eZ/7nuP4NS9Vhw9C1XAmVODKDPPSoiDdS5xl4AYWO7NR5oYucsG0qeYlHP0gr093TuUEMIk=}
conda_forge_output_validation: false
